#==============================================================================
# cleanupBLDC.cmd

epicsEnvUnset(MOT_U_MAX_MV)
epicsEnvUnset(MOT_I_MAX_MA)
epicsEnvUnset(MOT_I_RUN_MA)
epicsEnvUnset(MOT_POLE_PAIRS)
epicsEnvUnset(MOT_TRQ_CONST_MNM_P_A)
epicsEnvUnset(MOT_L_COIL)
epicsEnvUnset(MOT_COM_OFFSET_DEG)
epicsEnvUnset(MOT_THERM_CONST)
epicsEnvUnset(MOT_CURR_KP)
epicsEnvUnset(MOT_CURR_TI)
epicsEnvUnset(MOT_VELO_KP)
epicsEnvUnset(MOT_VELO_TI)
epicsEnvUnset(MOT_ROT_INERTIA_GCM2)
epicsEnvUnset(DRV_I_MAX_MA)
epicsEnvUnset(DRV_I_NOM_MA)
epicsEnvUnset(DRV_U_MAX_MV)
epicsEnvUnset(I_MAX_MA)
epicsEnvUnset(I_NOM_MA)
epicsEnvUnset(U_NOM_MV)
epicsEnvUnset(VELO_KP)
epicsEnvUnset(VELO_TI)
epicsEnvUnset(CURR_KP)
epicsEnvUnset(CURR_TI)
epicsEnvUnset(I_MAX_MA_VALID)
epicsEnvUnset(U_NOM_MV_VALID)
