#- Cleanup
epicsEnvUnset(MOT_I_MAX_MA)
epicsEnvUnset(MOT_I_RUN_MA)
epicsEnvUnset(MOT_I_STDBY_MA)
epicsEnvUnset(MOT_U_MAX_MV)
epicsEnvUnset(MOT_U_MV)
epicsEnvUnset(MOT_R_COIL_MOHM)
epicsEnvUnset(MOT_L_COIL_UH)
epicsEnvUnset(MOT_TRQ_MAX_NMM)
epicsEnvUnset(MOT_STEPS)
epicsEnvUnset(COMP_TYPE)
epicsEnvUnset(I_STDBY_MA)
epicsEnvUnset(I_RUN_MA)
epicsEnvUnset(CH_ID)
epicsEnvUnset(MACROS)
epicsEnvUnset(U_RUN_MV)
epicsEnvUnset(SLAVE_SCRIPT)
